# -*- coding: utf-8 -*-
"""ai.mini project.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105sh9Iy2ZjBcwzP-QIu13RA9R1HlWzAZ
"""

import random

# Track counts of the player's choices
player_choices = {"Rock": 0, "Paper": 0, "Scissor": 0}

# Mapping of choices
choices = {1: "Rock", 2: "Paper", 3: "Scissor"}
counters = {"Rock": "Paper", "Paper": "Scissor", "Scissor": "Rock"}  # Best counter moves

# Scores
player_score = 0
computer_score = 0

def predict_player_move():
    # Calculate probabilities based on player's past choices
    total = sum(player_choices.values())
    if total == 0:
        # If no data, choose randomly
        return random.choice(["Rock", "Paper", "Scissor"])
    # Calculate probability for each move
    probabilities = {move: count / total for move, count in player_choices.items()}
    # Predict the player's next move based on the highest probability
    predicted_move = max(probabilities, key=probabilities.get)
    return counters[predicted_move]  # Return the counter to the predicted move

print("1. Rock\n2. Paper\n3. Scissor\n4. Quit")

while True:
    player_input = input("Enter your choice (1-4): ")

    if player_input == '4':
        break

    if player_input in ['1', '2', '3']:
        player_choice = choices[int(player_input)]
        computer_choice = predict_player_move()

        # Print choices
        print(f"You chose {player_choice}")
        print(f"Computer chose {computer_choice}")

        # Update player's choice count
        player_choices[player_choice] += 1

        # Determine the outcome
        if player_choice == computer_choice:
            print("It's a Tie!")
        elif counters[player_choice] == computer_choice:
            print("You Lose!")
            computer_score += 1
        else:
            print("You Win!")
            player_score += 1

        # Display scores
        print(f"Your score: {player_score} | Computer score: {computer_score}\n")

    else:
        print("Enter a valid input (1-4)")

print("Game over!")